spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:25060}/${DB_NAME:defaultdb}?sslmode=require
    username: ${DB_USERNAME:doadmin}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 25
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: validate  # Never auto-update in production
    show-sql: false
    properties:
      hibernate:
        jdbc.batch_size: 20
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      retries: 3
      acks: all
      consumer:
        auto-offset-reset: earliest
        enable-auto-commit: true

      servlet:
        multipart:
          enabled: true
          max-file-size: 10MB
          max-request-size: 10MB

    server:
      port: ${PORT:8080}
      error:
        include-message: never
        include-binding-errors: never
        include-stacktrace: never
      compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 1024

api:
  external:
    base-url: ${EXTERNAL_API_BASE_URL:https://suppliers.htxstaging.com}
    api-key: ${EXTERNAL_API_KEY}
    header-name: ${EXTERNAL_API_HEADER_NAME:Authorization}
    header-prefix: ${EXTERNAL_API_HEADER_PREFIX:Bearer}
    timeout: ${EXTERNAL_API_TIMEOUT:10000}

logging:
  level:
    root: INFO
    com.example.driverevents: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized