spring:
  application:
    name: driverEvents

  datasource:
    url: jdbc:postgresql://localhost:5432/bookingdb
    username: postgres
    password: 4akaiMalko
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc.batch_size: 20
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

# Firebase config
firebase:
  config:
    path: src/main/resources/firebase-service-account.json

api:
  external:
    base-url: https://suppliers.htxstaging.com
    api-key: dev-test-key-12345
    header-name: Authorization
    header-prefix: Bearer
    timeout: 10000

logging:
  level:
    root: INFO
    com.example.driverevents: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG