spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

api:
  external:
    base-url: https://api.example.com/v1
    timeout: 5000