spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingdb
    username: postgres
    password: 4akaiMalko
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

api:
  external:
    base-url: https://api.example.com/v1
    timeout: 5000

excel:
  test-data:
    bookings: src/main/resources/test-data/bookings.xlsx
    drivers: src/main/resources/test-data/drivers.xlsx
    destinations: src/main/resources/test-data/destinations.xlsx
    vehicles: src/main/resources/test-data/vehicles.xlsx